# Generated by Django 5.0.1 on 2024-04-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_personal_phone_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(default="User", max_length=120),
        ),
    ]
