# Generated by Django 5.0.1 on 2024-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_invitationtoken_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitationtoken",
            name="user",
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="email",
            field=models.CharField(default="", max_length=128),
        ),
    ]
