# Generated by Django 5.0.1 on 2024-05-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_invitationtoken_user_invitationtoken_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="role",
            field=models.CharField(default="User", max_length=120),
        ),
    ]
