# Generated by Django 5.0.1 on 2024-06-17 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_invitationtoken_invited_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("language", models.CharField(max_length=50, unique=True)),
                ("dialect", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranslationPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_text", models.CharField(max_length=1000)),
                ("dst_text", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dst_lang",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dst_pairs",
                        to="main.lang",
                    ),
                ),
                (
                    "src_lang",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="src_pairs",
                        to="main.lang",
                    ),
                ),
            ],
        ),
    ]
