# Generated by Django 5.0.1 on 2024-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_lang_translationpair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lang",
            name="language",
        ),
        migrations.AddField(
            model_name="lang",
            name="writing",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translationpair",
            name="correct",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lang",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="lang",
            name="dialect",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
