# Generated by Django 5.0.1 on 2024-06-27 15:39

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_translationpair_dst_text_and_more"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="translationpair",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["src_text", "dst_text"], name="textIndex"
            ),
        ),
    ]
