# Generated by Django 5.0.1 on 2024-06-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_translationpair_textindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationpair",
            name="dst_text",
            field=models.CharField(db_index=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="translationpair",
            name="src_text",
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
