# Generated by Django 5.0.1 on 2024-06-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_remove_translationpair_textindex_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="translationpair",
            name="text_upper_index",
        ),
    ]
