# Generated by Django 5.0.1 on 2024-06-27 20:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_remove_translationpair_text_upper_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationpair",
            name="dst_text",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="translationpair",
            name="src_text",
            field=models.CharField(max_length=10000),
        ),
    ]
