# Generated by Django 5.0.1 on 2024-06-27 20:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_translationpair_dst_text_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="translationpair",
            index=models.Index(
                django.db.models.functions.text.Upper("src_text"),
                django.db.models.functions.text.Upper("dst_text"),
                name="text_index",
            ),
        ),
    ]
