# Generated by Django 5.0.1 on 2024-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_translationpair_model_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(default="", max_length=128, unique=True)),
                ("first_name", models.CharField(default="", max_length=120)),
                ("last_name", models.CharField(default="", max_length=128)),
                ("reason", models.CharField(max_length=10000, null=True)),
                ("approved", models.BooleanField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
