# Generated by Django 5.0.1 on 2024-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_requestaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestaccess",
            name="approved",
            field=models.BooleanField(),
        ),
    ]
