# Generated by Django 5.0.1 on 2024-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_requestaccess_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestaccess",
            name="approved",
            field=models.BooleanField(null=True),
        ),
    ]
