# Generated by Django 5.0.1 on 2024-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_invitationtoken_invited_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="email",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="requestaccess",
            name="email",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="requestaccess",
            name="first_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="requestaccess",
            name="last_name",
            field=models.CharField(max_length=128),
        ),
    ]
