# Generated by Django 5.1.1 on 2024-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="first_name",
            field=models.CharField(default="Seba", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="last_name",
            field=models.CharField(default="Ricke", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="organization",
            field=models.CharField(default="Cenia", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestaccess",
            name="organization",
            field=models.CharField(default="Cenia", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Administrador"),
                    ("NativeAdmin", "Administrador Nativo"),
                    ("Annotator", "Anotador"),
                    ("Native", "Nativo"),
                    ("User", "Usuario"),
                ],
                default="User",
                max_length=120,
            ),
        ),
    ]
