# Generated by Django 5.1.1 on 2024-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_profile_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="organization",
            field=models.CharField(default="", max_length=120),
        ),
    ]
