# Generated by Django 5.1.1 on 2024-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_profile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="lang",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
