# Generated by Django 5.1.1 on 2024-10-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_lang_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationpair",
            name="model_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="translationpair",
            name="model_version",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
