# Generated by Django 5.1.1 on 2024-10-23 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_alter_invitationtoken_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
