# Generated by Django 5.1.1 on 2024-10-23 18:07

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_profile_date_joined"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="translationpair",
            index=models.Index(
                django.db.models.functions.text.Upper("src_text"),
                django.db.models.functions.text.Upper("dst_text"),
                name="text_index",
            ),
        ),
    ]
