# Generated by Django 5.1.1 on 2024-10-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_translationpair_validated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationpair",
            name="validated",
            field=models.BooleanField(default=False),
        ),
    ]
