# Generated by Django 5.1.1 on 2024-12-04 21:10

import django.db.models.deletion
from django.db import migrations, models


def convert_dialect_to_foreign_key(apps, schema_editor):
    Lang = apps.get_model('main', 'Lang')
    Dialect = apps.get_model('main', 'Dialect')
    
    # We need to update dialects to ids, to be then updated to the foreign key
    
    # Create a temporary field to store dialect IDs
    dialect_map = {}
    
    # First create all Dialect objects and store their IDs
    for lang in Lang.objects.all():
        if lang.dialect:  # If there's an existing dialect string
            dialect, _ = Dialect.objects.get_or_create(
                code=lang.dialect,
                defaults={'name': lang.dialect}
            )
            dialect_map[lang.id] = dialect.id
    
    # Now update the Lang records with the dialect IDs
    for lang_id, dialect_id in dialect_map.items():
        Lang.objects.filter(id=lang_id).update(dialect=dialect_id)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_alter_translationpair_validated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="lang",
            name="writing",
        ),
        # Run the data migration before changing the field type
        migrations.RunPython(convert_dialect_to_foreign_key),
        migrations.AlterField(
            model_name="lang",
            name="dialect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.dialect",
            ),
        ),
        migrations.AddField(
            model_name="lang",
            name="script",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.script",
            ),
        ),
        migrations.AddIndex(
            model_name="lang",
            index=models.Index(fields=["code"], name="main_lang_code_fc743c_idx"),
        ),
    ]
