# Generated by Django 5.1.1 on 2024-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_dialect_script_remove_lang_writing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lang",
            name="is_native",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lang",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
