services:
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
    command: --private-ip ${INSTANCE_CONNECTION_NAME} --credentials-file=/secrets/cloudsql/credentials.json --address 0.0.0.0 --port ${DB_PORT}
    networks:
      - sql
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    volumes:
      - ./secrets/sql-credentials.json:/secrets/cloudsql/credentials.json

  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      # override db_host value for debug
      - DB_HOST=cloudsql-proxy
    networks:
      - sql
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "cloudsql-proxy"

networks:
  sql:
    name: sql
    driver: bridge
